# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm ci
      # - name: Run Unit Test
      #   run: npm test
      # - name: Build
      #   run: npm run build
      - name: Read GitHub Ref
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set Package Version
        run: npm version ${{ env.tag }} --no-git-tag-version
      - name: Authenticate with Google
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Authenticate docker with gcloud
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Docker Build
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.APP_REPO_NAME }}/${{ secrets.APP_NAME }}:${{ env.tag }} .
      - name: Push Docker Image to GCR
        run: |-
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.APP_REPO_NAME }}/${{ secrets.APP_NAME }}:${{ env.tag }}
